AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ticketera Cloud - Checkout Service

Parameters:
  CognitoUserPoolArn:
    Type: String
    Default: "arn:aws:cognito-idp:us-east-1:000000000000:userpool/local_UserPool"
    Description: ARN del Cognito User Pool para validacion JWT

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: provided.al2023
    Architectures:
      - arm64

Resources:
  CheckoutApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        ApiKeyRequired: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn
            Identity:
              Header: Authorization
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  CheckoutFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      Events:
        PostCheckout:
          Type: Api
          Properties:
            RestApiId: !Ref CheckoutApi
            Path: /checkout
            Method: POST
            Auth:
              ApiKeyRequired: true
              Authorizer: CognitoAuthorizer   # API Key + JWT: endpoint crítico de pago
        GetSwagger:
          Type: Api
          Properties:
            RestApiId: !Ref CheckoutApi
            Path: /swagger.json
            Method: GET
            Auth:
              ApiKeyRequired: false


