AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ticketera Cloud - Shows Service

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: provided.al2023
    Architectures:
      - arm64

Resources:
  ShowsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        ApiKeyRequired: false
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"


  ShowsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      Environment:
        Variables:
          SHOWS_TABLE_NAME: !Ref ShowsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ShowsTable
      Events:
        GetShowsByEventId:
          Type: Api
          Properties:
            RestApiId: !Ref ShowsApi
            Path: /events/{eventId}/shows
            Method: GET
            Auth:
              ApiKeyRequired: true
        GetSwagger:
          Type: Api
          Properties:
            RestApiId: !Ref ShowsApi
            Path: /swagger.json
            Method: GET
            Auth:
              ApiKeyRequired: false

  ShowsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: event_id
        Type: String

