basePath: /
definitions:
  domain.CheckoutRequest:
    properties:
      event_id:
        type: string
      method:
        type: string
      seats:
        items:
          type: string
        type: array
    type: object
  domain.CheckoutResponse:
    properties:
      message:
        type: string
      order_id:
        type: string
      status:
        type: string
    type: object
host: localhost:3004
info:
  contact: {}
  description: Ticketera Cloud Checkout Microservice API
  title: Checkout API
  version: "1.0"
paths:
  /checkout:
    post:
      consumes:
      - application/json
      description: Validates payload and triggers async queue for payment
      parameters:
      - description: Checkout Request object
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.CheckoutRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/domain.CheckoutResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Process a checkout
      tags:
      - checkout
swagger: "2.0"
