basePath: /
definitions:
  domain.Seat:
    properties:
      id:
        type: string
      number:
        type: integer
      row:
        type: string
      status:
        description: available, occupied, processing
        type: string
    type: object
host: localhost:3005
info:
  contact: {}
  description: Ticketera Cloud Seats Microservice API
  title: Seats API
  version: "1.0"
paths:
  /events/{eventId}/seats:
    get:
      description: Retrieve real-time seat status for a given event ID
      parameters:
      - description: Event ID
        in: path
        name: eventId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Seat'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get seats for an event
      tags:
      - seats
swagger: "2.0"
