AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ticketera Cloud - Events Service

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: provided.al2023
    Architectures:
      - arm64

Resources:
  EventsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        
  EventsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      Events:
        GetEvents:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApi
            Path: /events
            Method: GET
        GetEventById:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApi
            Path: /events/{id}
            Method: GET
        GetSwagger:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApi
            Path: /swagger.json
            Method: GET
