basePath: /
host: localhost:3000
info:
  contact: {}
  description: Ticketera Cloud Events Microservice API
  title: Events API
  version: "1.0"
paths:
  /events:
    get:
      description: Retrieve events list or specific event by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get event(s)
      tags:
      - events
  /events/{id}:
    get:
      description: Retrieve events list or specific event by ID
      parameters:
      - description: Event ID
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get event(s)
      tags:
      - events
swagger: "2.0"
